-- 100UP CRM — system configurations. Phase B, §4.1-4.2 of the design.
--
-- This is what replaces the brand `if` statements. V46 repeats
-- `isSig = brand === 'Sigenergy'` across five cost functions, and encodes
-- component quantities as arithmetic: gatewayCount = ceil(invCount/3),
-- groundKitCost = invCount * 250, deyeBmsCost = invCount * 550. A third brand
-- cannot be expressed at all. Here a system option is rows, and adding one is
-- data entry.

create type public.qty_rule as enum (
  'per_system', 'per_inverter', 'per_n_inverters',
  'per_battery', 'per_n_batteries', 'per_panel', 'per_kw_solar'
);

create table public.system_configs (
  id           bigint generated by default as identity primary key,
  -- Narrows the product pickers and seeds the default label. Never enters the
  -- calculation — brand must not be able to disagree with the products chosen.
  brand_filter text    not null default '',
  label        text    not null,
  -- Parasitic draw, 24/7, drained from the battery. Moved off `assumptions`
  -- (sig_standby_w / deye_standby_w) as planned in A6.
  standby_w    numeric not null default 0,
  sort_order   smallint not null default 0,
  active       boolean not null default true
);

-- Inverter tiers this config can select from. The engine ranks them the way
-- _sig3phBest does today: fewest inverters, then lowest price, then largest kW.
-- A config is NOT phase-specific — see the components table for why.
create table public.system_config_inverters (
  id               bigint generated by default as identity primary key,
  config_id        bigint not null references public.system_configs (id) on delete cascade,
  stock_id         bigint not null references public.stocks (id) on delete restrict,
  -- Null inherits the global sizing rule; set to override for one tier.
  oversize_percent numeric,
  max_batteries    smallint,
  sort_order       smallint not null default 0,
  unique (config_id, stock_id)
);

create table public.system_config_batteries (
  id         bigint generated by default as identity primary key,
  config_id  bigint not null references public.system_configs (id) on delete cascade,
  stock_id   bigint not null references public.stocks (id) on delete restrict,
  is_default boolean not null default true,
  unique (config_id, stock_id)
);

-- The table that removes the hardcoding.
--
-- PHASE IS A SCOPE, NOT AN ASSIGNMENT. Comparing V46's single- and three-phase
-- engines line by line, only three things differ: the inverter products, the
-- Sigenergy gateway model, and the oversize rule. Panels, batteries, mounting
-- kit, Deye PDU/Base, fixed costs, rebates, margin and GST are identical. So a
-- config serves both phases and only the rows that genuinely vary are scoped —
-- otherwise a dozen rows get cloned to change two.
create table public.system_config_components (
  id          bigint generated by default as identity primary key,
  config_id   bigint  not null references public.system_configs (id) on delete cascade,
  stock_id    bigint  not null references public.stocks (id) on delete restrict,
  rule        public.qty_rule not null default 'per_system',
  qty         numeric  not null default 1,   -- multiplier
  divisor     smallint not null default 1,   -- the n in per_n_*; ceil() applied
  phase_scope public.electrical_phase not null default 'na',  -- 'na' = both
  sort_order  smallint not null default 0
);

-- ── Seed the two current options from the product catalogue ───────────
insert into public.system_configs (brand_filter, label, standby_w, sort_order)
  select 'Sigenergy', 'Sigenergy', a.sig_standby_w, 1 from public.assumptions a where a.id = 1
  union all
  select 'Deye', 'Deye', a.deye_standby_w, 2 from public.assumptions a where a.id = 1;

-- Inverter tiers. Phase comes from the product, so both phases sit in one
-- config and the engine filters by the quote's phase.
insert into public.system_config_inverters (config_id, stock_id, sort_order)
select c.id, s.id,
       row_number() over (partition by c.id order by s.phase, s.planning_cost)
from public.system_configs c
join public.manufacturers m on m.brand = c.brand_filter
join public.stocks s on s.manufacturer_id = m.id
where s.product_type = 'inverter' and s.active;

insert into public.system_config_batteries (config_id, stock_id, is_default)
select c.id, s.id, s.name in ('SigenStor BAT 10.0', 'Deye AI-W5.1-B')
from public.system_configs c
join public.manufacturers m on m.brand = c.brand_filter
join public.stocks s on s.manufacturer_id = m.id
where s.product_type = 'battery' and s.active;

-- Components, replacing the hardcoded arithmetic one row at a time:
--   ceil(invCount/3) x sigGatewayCost  ->  per_n_inverters, divisor 3, scoped
--   invCount x sigGroundKitCost        ->  per_inverter, both phases
--   invCount x deyeBmsCost (one number, two products) -> two per_inverter rows
insert into public.system_config_components (config_id, stock_id, rule, qty, divisor, phase_scope, sort_order)
-- Casts are explicit: in a UNION the branches must agree on type, and an
-- untyped literal is text, not the enum.
select c.id, s.id, 'per_n_inverters'::public.qty_rule, 1, 3,
       s.phase, 1::smallint
from public.system_configs c
join public.manufacturers m on m.brand = c.brand_filter
join public.stocks s on s.manufacturer_id = m.id
where s.product_type = 'gateway' and s.active

union all
select c.id, s.id, 'per_inverter'::public.qty_rule, 1, 1, 'na'::public.electrical_phase, 2::smallint
from public.system_configs c
join public.manufacturers m on m.brand = c.brand_filter
join public.stocks s on s.manufacturer_id = m.id
where s.product_type = 'mounting' and s.active

union all
select c.id, s.id, 'per_inverter'::public.qty_rule, 1, 1, 'na'::public.electrical_phase, 3::smallint
from public.system_configs c
join public.manufacturers m on m.brand = c.brand_filter
join public.stocks s on s.manufacturer_id = m.id
where s.product_type = 'bms' and s.active;

-- ── RLS, grants, realtime ─────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'system_configs', 'system_config_inverters',
    'system_config_batteries', 'system_config_components'
  ]
  loop
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select on public.%I to authenticated', t);
    execute format('grant insert, update, delete on public.%I to authenticated', t);
    execute format('grant usage, select on sequence public.%I_id_seq to authenticated', t);
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy "%s_select_all" on public.%I for select to authenticated using (true)', t, t);
    execute format('create policy "%s_write_admin" on public.%I for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()))', t, t);
    execute format('alter publication supabase_realtime add table public.%I', t);
  end loop;
end $$;

comment on column public.system_config_components.phase_scope is
  'Which phase(s) this component applies to. ''na'' = both, which is the common case (mounting kit, stack base). Only set where the product genuinely differs by phase, e.g. the two Sigenergy gateways.';
comment on column public.system_config_components.rule is
  'How the quantity is derived. Replaces hardcoded arithmetic: a gateway is per_n_inverters/3, a mounting kit per_inverter, the Deye base per_inverter on two separate rows.';
