-- 100UP CRM — somewhere for Fred to put bugs and ideas while he tests.
--
-- He is testing now and feedback arrives by phone and email, where it gets
-- lost or half-remembered. This is a place to put it that costs him one
-- click from wherever he noticed the problem, and gives Vanessa a list
-- instead of a scroll-back.
--
-- SCOPE, deliberately small:
--
--   No screenshots in v1. They would be the first Supabase Storage use in
--   this project — a bucket, signed URLs, RLS on storage.objects, upload UI,
--   image handling — for perhaps a fifth of the value. It also cuts against a
--   decision already made: wishlist W1 (file supplier documents) was closed
--   "not needed", and supplier_documents deliberately stores extracted data
--   rather than files. "The CRM does not hold files" is an existing
--   principle. The auto-captured screen plus Fred's own words usually gets
--   there, and screenshots are purely additive later.
--
--   Three live statuses, not four. `blocked` belongs in the admin note; it is
--   rare and it is not a state anyone acts on differently. `started` earns
--   its place for a reason that has nothing to do with tracking: it is how
--   Fred sees that Vanessa has picked something up, which is exactly the
--   "he cannot see that I have done work" problem.
--
-- NOT a replacement for docs/bugs.md. That stays the engineering register.
-- Anything here that needs a code fix gets promoted by hand — which is why
-- `screen` is captured automatically: it is the context that makes the
-- promotion cheap.

create type public.feedback_kind as enum ('bug', 'idea');
create type public.feedback_status as enum ('open', 'started', 'done', 'wont_do');

create table public.feedback_items (
  id          bigint generated by default as identity primary key,
  kind        public.feedback_kind   not null default 'bug',
  title       text   not null,
  details     text   not null default '',
  -- Which screen he was on, taken from Shell's `page` state. Captured rather
  -- than asked: "where were you" is the question people answer worst and it
  -- is the one that matters most when reproducing something.
  screen      text   not null default '',
  status      public.feedback_status not null default 'open',
  -- Vanessa's reply. Fred can read it, which is half the point — it closes
  -- the loop without an email.
  admin_note  text   not null default '',
  created_by  uuid   references public.profiles (id) on delete set null default auth.uid(),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  resolved_at timestamptz
);

create index feedback_items_status_idx on public.feedback_items (status, created_at desc);

-- Convention 5. The ALTER DEFAULT PRIVILEGES rule on this project hands
-- anon and authenticated ALL on every new table in public, so the grants
-- below do not describe the outcome unless the revoke comes first.
-- docs/bugs.md #13.
revoke all on public.feedback_items from anon, authenticated;
grant select, insert, update on public.feedback_items to authenticated;
grant usage, select on sequence public.feedback_items_id_seq to authenticated;

alter table public.feedback_items enable row level security;

-- Admin-only throughout, which today means Fred and Vanessa. Installers are
-- read-only elsewhere in the app and have no reason to file tickets: their
-- instruction from Fred is to ring him.
create policy "feedback_items_select_admin" on public.feedback_items
  for select to authenticated
  using ((select private.is_admin()));

create policy "feedback_items_insert_admin" on public.feedback_items
  for insert to authenticated
  with check ((select private.is_admin()));

create policy "feedback_items_update_admin" on public.feedback_items
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

-- No delete policy. A withdrawn item becomes 'wont_do' with a note saying
-- why; deleting it loses the fact that it was ever raised, which is the
-- thing a list like this exists to keep.

-- Keeps updated_at / resolved_at honest without the UI having to remember.
create or replace function private.touch_feedback_item()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  if new.status in ('done', 'wont_do') and old.status not in ('done', 'wont_do') then
    new.resolved_at := now();
  elsif new.status not in ('done', 'wont_do') then
    new.resolved_at := null;
  end if;
  return new;
end;
$$;

create trigger touch_feedback_item
  before update on public.feedback_items
  for each row execute function private.touch_feedback_item();

-- So a new item reaches an open tab immediately — data.tsx already subscribes
-- to every change in `public`.
alter publication supabase_realtime add table public.feedback_items;
