-- 100UP CRM — outbound email log.
--
-- Metadata only, never the body: the body lives in CyberPersons and in the
-- sender's own mailbox. This row is the CRM fact "we sent X to Y, and here is
-- what happened to it".
--
-- Two columns BW-CRM does not have, both deliberate:
--
--   status / error_message — BW-CRM logs only successes, and its customer
--   screen renders a hardcoded tick rather than reading a column. A send that
--   fails there returns 502 and leaves no trace at all, which is exactly the
--   case you most want a record of. Here a failure is logged too.
--
--   provider_status — whatever CyberPersons called it, stored verbatim
--   alongside our own two-value outcome. Their vocabulary ('queued',
--   'delivered', …) is not documented well enough to put behind a CHECK, and
--   a constraint that rejects a real provider response would fail the send
--   log rather than record it.
--
-- provider_message_id is the hook for matching replies later, when the Gmail
-- sync lands and this becomes the outbound half of a two-way customer thread.

create table public.email_sends (
  id                   bigint generated by default as identity primary key,
  customer_id          bigint references public.customers (id) on delete set null,
  job_id               bigint references public.jobs (id) on delete set null,
  purchase_order_id    bigint references public.purchase_orders (id) on delete set null,
  screen_type          text not null default 'customer'
                       check (screen_type in ('customer', 'job', 'purchase_order', 'test')),
  to_address           text not null default '',
  cc_address           text not null default '',
  subject              text not null,
  status               text not null default 'sent'
                       check (status in ('sent', 'failed')),
  provider_status      text,
  provider_message_id  text,
  error_message        text,
  sent_at              timestamptz not null default now()
);

create index email_sends_customer_sent_at_idx
  on public.email_sends (customer_id, sent_at desc);

create index email_sends_job_sent_at_idx
  on public.email_sends (job_id, sent_at desc)
  where job_id is not null;

create index email_sends_provider_message_id_idx
  on public.email_sends (provider_message_id)
  where provider_message_id is not null;

alter table public.email_sends enable row level security;

-- Admin only. Installers see assigned jobs, not customer correspondence.
-- Inserts come from the send-email Edge Function on the service role, so
-- there is deliberately no insert policy.
create policy "email_sends_select_admin"
  on public.email_sends for select to authenticated
  using ((select private.is_admin()));

grant select on public.email_sends to authenticated;

comment on table public.email_sends is
  'Outbound email log — metadata only, never the body. Written by the send-email Edge Function on the service role; failures are logged as well as successes.';
