-- 100UP CRM — break the 45-column `assumptions` singleton into real settings.
--
-- A6 of docs/archive/phase-a-implementation-plan.md; §4.3-4.7 of the configurator
-- design. This is the item that removes the reason to open V46 to change a
-- price, and with it the standing risk that the old file and the database
-- disagree about cost (2026-07-29 status doc, §5 "Two systems in parallel").
--
-- Three fates for the original 45 values:
--   MOVED    — genuinely global business settings, now in the tables below
--   DROPPED  — superseded by the product catalogue in A3/A4. Costs and specs
--              live on the product now; leaving the columns would be a second
--              source of truth for the same fact
--   KEPT     — load_profile and the two standby-draw figures stay on
--              `assumptions` until Phase B, when standby moves onto
--              system_configs and that table becomes purely simulation input

-- Shared version-bump trigger, mirroring private.bump_assumptions_version()
-- but reusable — seven tables would otherwise need seven near-identical ones.
create or replace function private.bump_settings_version()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;

-- ── Pricing ───────────────────────────────────────────────────────────
create table public.pricing_settings (
  id         smallint primary key default 1 check (id = 1),
  margin     numeric not null default 0.30,
  gst        numeric not null default 0.10,
  version    integer not null default 1,
  updated_at timestamptz not null default now()
);

-- ── Rebates ───────────────────────────────────────────────────────────
create table public.rebate_settings (
  id                smallint primary key default 1 check (id = 1),
  solar_stc_per_kw  numeric not null default 6.8,
  solar_stc_price   numeric not null default 38,
  battery_stc_price numeric not null default 38,
  version           integer not null default 1,
  updated_at        timestamptz not null default now()
);

-- Replaces battery_tier1/2/3 AND the 14/28/50 kWh band boundaries that were
-- hardcoded in batteryStcCount() (V46 line 2044). The boundaries matter as
-- much as the rates — federal rebate tiers change by legislation, and moving
-- 14 kWh to 15 was previously a code edit.
create table public.battery_rebate_tiers (
  id          bigint generated by default as identity primary key,
  from_kwh    numeric not null,
  to_kwh      numeric,            -- null = no upper bound
  stc_per_kwh numeric not null,
  sort_order  smallint not null default 0
);

-- ── Sizing rules ──────────────────────────────────────────────────────
-- Engineering/regulatory limits, not products, so these stay typed numbers.
-- Per-tier overrides land on system_config_inverters in Phase B.
create table public.sizing_rules (
  id                         smallint primary key default 1 check (id = 1),
  solar_oversize_percent     numeric  not null default 200,
  solar_oversize_3ph_percent numeric  not null default 160,
  max_batteries_per_inverter smallint not null default 6,
  min_inverters              smallint not null default 1,
  version                    integer  not null default 1,
  updated_at                 timestamptz not null default now()
);

-- ── Fixed site costs (repeater) ───────────────────────────────────────
-- Was four fixed columns; now rows, so Fred can add a fifth without a
-- schema change. No stock_id: linking "small parts" to a real consumables
-- product was considered and dropped — Fred does not want consumables
-- tracked at that level, and an unused nullable FK invites confusion.
create table public.fixed_site_costs (
  id         bigint generated by default as identity primary key,
  label      text    not null,
  amount     numeric not null default 0 check (amount >= 0),
  active     boolean not null default true,
  sort_order smallint not null default 0
);

-- ── Panels ────────────────────────────────────────────────────────────
-- Wattage, cost, manufacturer and model all come from the linked product now;
-- only the two install rates are settings.
create table public.panel_settings (
  id                   smallint primary key default 1 check (id = 1),
  stock_id             bigint references public.stocks (id) on delete restrict,
  install_cost_per_w   numeric not null default 0.35,
  roof_frame_per_panel numeric not null default 50,
  version              integer not null default 1,
  updated_at           timestamptz not null default now()
);

-- ── Ground mount ──────────────────────────────────────────────────────
-- Labour and plant are genuinely rates, not products. ballpark_frame_per_panel
-- is TEMPORARY: the design (§5) has frame cost derived from a GM kit of real
-- products, with the kit caching a ballpark for quotes made before the array
-- is measured. gm_kits arrives in Phase C; until then this holds the flat
-- figure so early-stage ground-mount quoting keeps working.
create table public.ground_mount_settings (
  id                        smallint primary key default 1 check (id = 1),
  labour_per_panel          numeric not null default 150,
  machinery_fixed           numeric not null default 1000,
  ballpark_frame_per_panel  numeric not null default 150,
  version                   integer not null default 1,
  updated_at                timestamptz not null default now()
);

-- ── Seed everything from the live assumptions row ─────────────────────
-- Values carry across exactly, so nothing reprices on deploy.
insert into public.pricing_settings (id, margin, gst)
  select 1, a.margin, a.gst from public.assumptions a where a.id = 1;

insert into public.rebate_settings (id, solar_stc_per_kw, solar_stc_price, battery_stc_price)
  select 1, a.solar_stc_per_kw, a.solar_stc_price, a.battery_stc_price
  from public.assumptions a where a.id = 1;

insert into public.battery_rebate_tiers (from_kwh, to_kwh, stc_per_kwh, sort_order)
  select 0,  14, a.battery_tier1, 1 from public.assumptions a where a.id = 1
  union all
  select 14, 28, a.battery_tier2, 2 from public.assumptions a where a.id = 1
  union all
  select 28, 50, a.battery_tier3, 3 from public.assumptions a where a.id = 1;

insert into public.sizing_rules (id, solar_oversize_percent, solar_oversize_3ph_percent, max_batteries_per_inverter, min_inverters)
  select 1, a.solar_oversize_percent, a.solar_oversize_3ph_percent, a.max_batt_per_inverter, a.min_inverters
  from public.assumptions a where a.id = 1;

insert into public.fixed_site_costs (label, amount, sort_order)
  select 'Small parts',         a.small_parts,        1 from public.assumptions a where a.id = 1
  union all
  select 'Installer sign off',  a.installer_sign_off, 2 from public.assumptions a where a.id = 1
  union all
  select 'CES',                 a.ces,                3 from public.assumptions a where a.id = 1
  union all
  select 'Fixed labour',        a.labour_fixed,       4 from public.assumptions a where a.id = 1;

insert into public.panel_settings (id, stock_id, install_cost_per_w, roof_frame_per_panel)
  select 1,
         (select s.id from public.stocks s where s.product_type = 'panel' order by s.id limit 1),
         a.panel_install_per_w, a.panel_frame
  from public.assumptions a where a.id = 1;

insert into public.ground_mount_settings (id, labour_per_panel, machinery_fixed, ballpark_frame_per_panel)
  select 1, a.gm_labour_per_panel, a.gm_machinery_fixed, a.gm_frame_per_panel
  from public.assumptions a where a.id = 1;

-- ── Strip `assumptions` back to simulation input ──────────────────────
-- Everything moved above, plus everything the product catalogue superseded.
-- Keeping any of these would mean two places to change one number, which is
-- the exact failure this whole phase exists to remove.
alter table public.assumptions
  drop column margin, drop column gst,
  drop column solar_stc_per_kw, drop column solar_stc_price, drop column battery_stc_price,
  drop column battery_tier1, drop column battery_tier2, drop column battery_tier3,
  drop column solar_oversize_percent, drop column solar_oversize_3ph_percent,
  drop column max_batt_per_inverter, drop column min_inverters,
  drop column small_parts, drop column installer_sign_off, drop column ces, drop column labour_fixed,
  drop column panel_install_per_w, drop column panel_frame,
  drop column gm_frame_per_panel, drop column gm_labour_per_panel, drop column gm_machinery_fixed,
  -- superseded by the product catalogue (A3/A4)
  drop column panel_w, drop column panel_cost, drop column panel_mfr, drop column panel_model,
  drop column sig_battery_kwh, drop column sig_battery_cost,
  drop column deye_battery_kwh, drop column deye_battery_cost,
  drop column sig_inverter_cost, drop column sig_single_inverter_cost,
  drop column deye_inverter_cost, drop column deye_single_inverter_cost,
  drop column deye_3ph_inverter_cost, drop column deye_bms_cost,
  drop column sig_gateway_cost, drop column sig_ground_kit_cost,
  drop column sig_3ph_15kw_cost, drop column sig_3ph_20kw_cost,
  drop column sig_3ph_30kw_cost, drop column sig_3ph_gateway_cost;

comment on table public.assumptions is
  'Simulation input only. Everything else moved to the settings tables (A6) or onto products (A3/A4). sig_standby_w / deye_standby_w stay here until Phase B moves them onto system_configs.';

-- ── Triggers, RLS, grants, realtime ───────────────────────────────────
create trigger b_bump_pricing_settings_version       before update on public.pricing_settings       for each row execute function private.bump_settings_version();
create trigger b_bump_rebate_settings_version        before update on public.rebate_settings        for each row execute function private.bump_settings_version();
create trigger b_bump_sizing_rules_version           before update on public.sizing_rules           for each row execute function private.bump_settings_version();
create trigger b_bump_panel_settings_version         before update on public.panel_settings         for each row execute function private.bump_settings_version();
create trigger b_bump_ground_mount_settings_version  before update on public.ground_mount_settings  for each row execute function private.bump_settings_version();

do $$
declare t text;
begin
  foreach t in array array[
    'pricing_settings', 'rebate_settings', 'battery_rebate_tiers',
    'sizing_rules', 'fixed_site_costs', 'panel_settings', 'ground_mount_settings'
  ]
  loop
    -- Everyone authenticated reads (quoting needs it); only admins write.
    execute format('revoke all on public.%I from anon', t);
    execute format('grant select on public.%I to authenticated', t);
    execute format('grant insert, update, delete on public.%I to authenticated', t);
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy "%s_select_all" on public.%I for select to authenticated using (true)', t, t);
    execute format('create policy "%s_write_admin" on public.%I for all to authenticated using ((select private.is_admin())) with check ((select private.is_admin()))', t, t);
    execute format('alter publication supabase_realtime add table public.%I', t);
  end loop;
end $$;

-- Repeater tables need their sequences too.
grant usage, select on sequence public.battery_rebate_tiers_id_seq to authenticated;
grant usage, select on sequence public.fixed_site_costs_id_seq to authenticated;
