-- 100UP CRM — Phase 1 migration 1/3: enums, tables, seed data
-- Ground truth: 100UP_suite_V46.html (PIPELINE lines 4623-4630, data shapes
-- verified against the app code and the 2026-06-25 JSON export).

-- Private schema for security-definer helpers (not exposed via the Data API).
create schema if not exists private;

-- ── Enums ──────────────────────────────────────────────────────────────
create type public.job_type as enum ('install', 'service');
create type public.user_role as enum ('admin', 'installer');
create type public.job_stock_item_status as enum ('pending', 'assigned', 'consumed');
create type public.ces_category as enum ('battery', 'inverter', 'panel', 'other');

-- ── pipeline_steps ─────────────────────────────────────────────────────
-- Replaces the hardcoded PIPELINE/SOFF/TOTAL constants. The composite FK
-- from jobs makes an invalid (stage, step) combination structurally
-- impossible, which the old app never guarded against.
create table public.pipeline_steps (
  stage      smallint not null,
  step       smallint not null,
  stage_name text     not null,
  step_name  text     not null,
  ordinal    smallint not null unique,
  primary key (stage, step)
);

insert into public.pipeline_steps (stage, step, stage_name, step_name, ordinal) values
  (1, 0, 'Communication',      'First contact',         0),
  (1, 1, 'Communication',      'Info collection',       1),
  (1, 2, 'Communication',      'System proposals',      2),
  (1, 3, 'Communication',      'Customer selects',      3),
  (2, 0, 'Quoting',            'Quote in Xero',         4),
  (2, 1, 'Quoting',            'Send quote',            5),
  (2, 2, 'Quoting',            'Deposit received',      6),
  (3, 0, 'Installation',       'Job info to installer', 7),
  (3, 1, 'Installation',       'Date booked',           8),
  (3, 2, 'Installation',       'Parts ordered',         9),
  (3, 3, 'Installation',       'Install in progress',  10),
  (3, 4, 'Installation',       'Install complete',     11),
  (4, 0, 'Compliance & close', 'CES submitted',        12),
  (4, 1, 'Compliance & close', 'Inspector review',     13),
  (4, 2, 'Compliance & close', 'Fixes complete',       14),
  (4, 3, 'Compliance & close', 'CES received',         15),
  (4, 4, 'Compliance & close', 'Rebate submitted',     16),
  (4, 5, 'Compliance & close', 'Rebate received',      17),
  (4, 6, 'Compliance & close', 'Job closed',           18);

-- ── profiles ───────────────────────────────────────────────────────────
create table public.profiles (
  id         uuid primary key references auth.users (id) on delete cascade,
  full_name  text not null default '',
  role       public.user_role not null default 'installer',
  created_at timestamptz not null default now()
);

-- ── suppliers ──────────────────────────────────────────────────────────
create table public.suppliers (
  id    bigint generated by default as identity primary key,
  name  text not null,
  phone text not null default '',
  email text not null default '',
  notes text not null default ''
);

-- Blocks re-introducing the EnergySpurt / "Energy Spurt " near-duplicate
-- class of supplier at least in its exact-after-normalization form.
create unique index suppliers_name_norm_uq on public.suppliers (lower(trim(name)));

-- ── stocks ─────────────────────────────────────────────────────────────
create table public.stocks (
  id          bigint generated by default as identity primary key,
  name        text not null,
  qty         integer not null default 0 check (qty >= 0),
  supplier_id bigint references public.suppliers (id) on delete set null
);

create index stocks_supplier_id_idx on public.stocks (supplier_id);

-- ── stock_ces_specs ────────────────────────────────────────────────────
-- Replaces the hardcoded getCesCatalog() map. No row = "not in the CES
-- catalogue" (same warning semantics as the old app). Values are set
-- per stock item, deliberately NOT derived from the calculator's global
-- Assumptions config.
create table public.stock_ces_specs (
  stock_id     bigint primary key references public.stocks (id) on delete cascade,
  category     public.ces_category not null,
  manufacturer text not null default '',
  model        text not null default '',
  kva          numeric,
  kw           numeric,
  kwh          numeric,
  watts        numeric,
  -- Sigenergy/Trina manufacturer names are unconfirmed against CEC
  -- listings; they import as verified = false.
  verified     boolean not null default false
);

-- ── jobs ───────────────────────────────────────────────────────────────
create table public.jobs (
  id                    bigint generated by default as identity primary key,
  name                  text not null,
  location              text not null default '',
  system_description    text not null default '',
  value                 numeric(12, 2) not null default 0,
  email                 text not null default '',
  phone                 text not null default '',
  contact_method        text not null default 'Email',
  job_type              public.job_type not null default 'install',
  stage                 smallint not null default 1,
  step                  smallint not null default 0,
  notes                 text not null default '',
  -- New field (no equivalent in the old single-user app): drives the
  -- installer-only-sees-assigned-jobs RLS model.
  assigned_installer_id uuid references public.profiles (id) on delete set null,
  date_booked           date,
  install_start         date,
  install_date          date,
  ces_submitted         date,
  ces_received          date,
  rebate_submitted      date,
  rebate_received       date,
  fixes_needed          boolean not null default false,
  -- Denormalized print document ({ref, issued, installer, vehicle, ...,
  -- customItems[]}); never queried across jobs, so jsonb by design.
  job_order             jsonb,
  -- Optimistic locking; bumped by trigger on every update.
  version               integer not null default 1,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  foreign key (stage, step) references public.pipeline_steps (stage, step)
);

create index jobs_assigned_installer_id_idx on public.jobs (assigned_installer_id);
create index jobs_stage_step_idx on public.jobs (stage, step);

-- ── job_stock_items ────────────────────────────────────────────────────
-- Replaces the three parallel arrays on the old job object:
--   pendingBom[]   -> status 'pending'
--   stockItems[]   -> status 'assigned'
--   stockConsumed[]-> status 'consumed'
create table public.job_stock_items (
  id          bigint generated always as identity primary key,
  job_id      bigint not null references public.jobs (id) on delete cascade,
  stock_id    bigint not null references public.stocks (id) on delete restrict,
  qty         integer not null check (qty > 0),
  notes       text not null default '',
  status      public.job_stock_item_status not null default 'assigned',
  created_at  timestamptz not null default now(),
  assigned_at timestamptz,
  consumed_at timestamptz
);

create index job_stock_items_job_id_idx on public.job_stock_items (job_id);
create index job_stock_items_stock_id_idx on public.job_stock_items (stock_id);
-- One live line per job x stock x status; lets the pending->assigned and
-- assigned->consumed transitions merge quantities with ON CONFLICT, the
-- same way applyPendingBom() merged by stockId.
create unique index job_stock_items_job_stock_status_uq
  on public.job_stock_items (job_id, stock_id, status);

-- ── receipts ───────────────────────────────────────────────────────────
-- supplier_id is a real FK (old app stored a bare name string). It stays
-- nullable because the old receive flow explicitly allows "no supplier".
create table public.receipts (
  id          bigint generated by default as identity primary key,
  occurred_at date not null default current_date,
  supplier_id bigint references public.suppliers (id) on delete set null,
  invoice_ref text not null default '',
  item_count  integer not null default 0,
  total_units integer not null default 0,
  created_at  timestamptz not null default now()
);

create index receipts_supplier_id_idx on public.receipts (supplier_id);

-- ── job_events ─────────────────────────────────────────────────────────
-- Notification-hook scaffolding. Written only by the stage-transition
-- RPCs for now; a stub Edge Function will consume it later.
create table public.job_events (
  id         bigint generated always as identity primary key,
  job_id     bigint not null references public.jobs (id) on delete cascade,
  event_type text not null,
  payload    jsonb not null default '{}'::jsonb,
  actor      uuid,
  created_at timestamptz not null default now()
);

create index job_events_job_id_idx on public.job_events (job_id);
