-- 100UP CRM — real manufacturers table, replacing free-text on stocks.
--
-- Reverses the PARK in docs/archive/schema-restructure-proposal.md §7. That deferral
-- was reasonable when the open question was "what else is stored per
-- manufacturer"; the data has since answered it.
--
-- WHY NOW: 17 stock rows carry SIX distinct manufacturer strings, and three
-- of them are the same company —
--   'Sigenergy Technology Co., Ltd'  (7 rows)
--   'Sigenergy Technology'           (1 row)
--   'Sigenergy'                      (1 row)
-- That is exactly the drift free text produces, and these strings go onto CES
-- compliance submissions.
--
-- THE MODELLING POINT: brand is NOT the legal entity. Deye's two strings are
-- not a typo — inverters are listed under Deye Inverter Technology and
-- batteries under Deye ESS Technology, genuinely different CEC entities. So
-- one brand can have several legal entities, and the table carries both:
-- pickers group by `brand`, CES reads `legal_name`.

create table public.manufacturers (
  id           bigint generated by default as identity primary key,
  -- Trading/brand name. Groups products in the configurator's pickers and
  -- seeds the default label on a system config.
  brand        text not null,
  -- Exact entity name as listed on the CEC. This is what goes on a CES form.
  legal_name   text not null default '',
  -- Whether legal_name has actually been checked against a CEC listing.
  -- Distinct from stocks.verified, which is per-MODEL (does this model string
  -- and standard match the listing). §7 of the restructure proposal worried
  -- about collapsing those two; they are kept separate here because they are
  -- different facts and buildCes needs both.
  cec_verified boolean not null default false,
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  -- One brand, many legal entities (see Deye above); the pair is unique.
  unique (brand, legal_name)
);

alter table public.stocks
  add column manufacturer_id bigint references public.manufacturers (id) on delete restrict;

-- Seed from the distinct values actually present, collapsing the three
-- Sigenergy spellings and preserving both Deye entities.
-- cec_verified follows CLAUDE.md: Deye verified; Sigenergy unconfirmed. Jinko
-- is marked UNVERIFIED despite CLAUDE.md listing it as verified, because the
-- stored value was the short name 'Jinko', not a legal entity — the full
-- string below is the documented example from docs/archive/2026-07_layout-specs/Assumptions.md and has not
-- been confirmed against a listing. Do not treat it as authoritative.
insert into public.manufacturers (brand, legal_name, cec_verified) values
  ('Sigenergy', 'Sigenergy Technology Co., Ltd',          false),
  ('Deye',      'NingBo Deye Inverter Technology Co Ltd', true),
  ('Deye',      'Ningbo Deye Ess Technology Co Ltd',      true),
  ('Jinko',     'Jinko Solar Co., Ltd',                   false);

-- Link existing stock to the collapsed entities.
update public.stocks s set manufacturer_id = m.id
from public.manufacturers m
where m.legal_name = 'Sigenergy Technology Co., Ltd'
  and s.manufacturer in ('Sigenergy Technology Co., Ltd', 'Sigenergy Technology', 'Sigenergy');

update public.stocks s set manufacturer_id = m.id
from public.manufacturers m
where m.legal_name = s.manufacturer
  and s.manufacturer in ('NingBo Deye Inverter Technology Co Ltd', 'Ningbo Deye Ess Technology Co Ltd');

update public.stocks s set manufacturer_id = m.id
from public.manufacturers m
where m.brand = 'Jinko' and s.manufacturer = 'Jinko';

-- Drop the two columns this replaces.
--   `manufacturer` — superseded by the FK. buildCes() is updated in the same
--     release to read legal_name through the join, so there is no window
--     where CES output is wrong.
--   `brand` — added hours ago in 20260811100001 and never populated or read.
--     Removed rather than left as a second, drifting source for the same fact.
alter table public.stocks
  drop column manufacturer,
  drop column brand;

create index stocks_manufacturer_id_idx on public.stocks (manufacturer_id);

-- RLS: same shape as other shared reference data — every authenticated user
-- reads (quoting and CES need it), only admins write.
revoke all on public.manufacturers from anon;
grant select on public.manufacturers to authenticated;
grant insert, update, delete on public.manufacturers to authenticated;
grant usage, select on sequence public.manufacturers_id_seq to authenticated;

alter table public.manufacturers enable row level security;

create policy "manufacturers_select_all" on public.manufacturers
  for select to authenticated
  using (true);

create policy "manufacturers_insert_admin" on public.manufacturers
  for insert to authenticated
  with check ((select private.is_admin()));

create policy "manufacturers_update_admin" on public.manufacturers
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

create policy "manufacturers_delete_admin" on public.manufacturers
  for delete to authenticated
  using ((select private.is_admin()));

alter publication supabase_realtime add table public.manufacturers;

comment on column public.manufacturers.brand is
  'Trading name. Groups products in configurator pickers. One brand may have several legal entities.';
comment on column public.manufacturers.legal_name is
  'Exact CEC-listed entity name — this is what appears on a CES submission.';
comment on column public.manufacturers.cec_verified is
  'Whether legal_name was checked against a CEC listing. Per-entity; stocks.verified is the per-model equivalent.';
