-- 100UP CRM — goods receipts, separated from purchase orders.
--
-- See docs/design/goods-receipt-design.md. The short version: `purchase_orders` has
-- been doing three jobs, and `receive_stock` writes a receipt as a fake closed
-- PO with NO purchase_order_items rows at all — so what was received is not
-- recorded anywhere, only the resulting stocks.qty increment.
--
-- Three concepts replace that:
--
--   the order    purchase_orders + purchase_order_items   (unchanged)
--   the receipt  goods_receipts  + goods_receipt_items    (a stock movement)
--   the document supplier_documents                       (the piece of paper)
--
-- The governing idea is that STOCK MOVES ONCE and PRICES CAN ARRIVE LATER.
-- A delivery docket moves the goods; the invoice turns up a fortnight later,
-- attaches to the same receipt, and fills in prices without touching stock
-- again. If there is only ever an invoice, it does both jobs.
--
-- Document-to-receipt is many-to-many, hence the join table: one invoice can
-- cover two deliveries (D2), and one delivery can be split across two
-- invoices.

-- ── stocks: landed cost alongside invoice cost ────────────────────────────
-- Two costs, deliberately. Folding freight into a single unit cost would
-- collapse "what did the supplier charge per unit" and "what did this cost me
-- landed" into one number, leaving neither recoverable (design §6).
alter table public.stocks
  add column last_landed_cost numeric not null default 0;

comment on column public.stocks.last_cost is
  'Ex-GST unit price from the most recent supplier invoice. Still hand-editable on the Stock page — see docs/feature-wishlist.md W2 for the two-writer problem that creates.';
comment on column public.stocks.last_landed_cost is
  'last_cost plus apportioned freight, from the most recent receipt. A snapshot, not a live figure — goods_receipt_items_landed computes the current value per line.';

-- ── supplier_documents ────────────────────────────────────────────────────
-- Check constraints rather than enums: the project uses both, and a CHECK is
-- cheaper to widen for values that are labels rather than state machines.
create table public.supplier_documents (
  id                   bigint generated by default as identity primary key,
  supplier_id          bigint not null references public.suppliers (id) on delete restrict,
  doc_type             text not null default 'invoice'
                       check (doc_type in ('docket', 'invoice', 'both')),
  -- The supplier's own reference. Blank is allowed: handwritten dockets often
  -- have none, and refusing the document over it helps nobody.
  supplier_ref         text not null default '',
  doc_date             date,

  -- Totals as PRINTED on the document, not as parsed by us. Comparing the two
  -- is what catches a page that did not scan (design §5).
  claimed_line_count   integer,
  claimed_total_units  numeric,

  subtotal_ex_gst      numeric,
  gst_amount           numeric,
  total_inc_gst        numeric,

  -- Freight is its own field and never a stock line. A freight line masquerading
  -- as stock acquires a quantity, gets received into stock on hand, and still
  -- cannot be apportioned across the lines it relates to (design §6).
  freight_ex_gst       numeric not null default 0,
  other_charges_ex_gst numeric not null default 0,

  -- Whether the printed LINE prices include GST, and how we decided. Resolved
  -- by reconciling the totals rather than guessing or asking (design §4);
  -- 'unknown' means nothing reconciled and a human must look.
  price_basis          text not null default 'unknown'
                       check (price_basis in ('ex_gst', 'inc_gst', 'mixed', 'unknown')),
  price_basis_source   text not null default 'reconciled'
                       check (price_basis_source in ('reconciled', 'manual')),

  notes                text not null default '',
  created_at           timestamptz not null default now(),
  created_by           uuid references public.profiles (id) on delete set null
);

-- The hard-stop half of duplicate detection (design §3.2), enforced in the
-- database rather than trusted to the UI. Blank refs are excluded, so several
-- unreferenced dockets from one supplier remain possible.
create unique index supplier_documents_supplier_ref_uniq
  on public.supplier_documents (supplier_id, lower(supplier_ref))
  where supplier_ref <> '';

create index supplier_documents_supplier_date_idx
  on public.supplier_documents (supplier_id, doc_date desc);

-- ── goods_receipts ────────────────────────────────────────────────────────
create table public.goods_receipts (
  id                bigint generated by default as identity primary key,
  supplier_id       bigint not null references public.suppliers (id) on delete restrict,
  -- Nullable on purpose: receiving goods with no matching order is normal,
  -- not an error state to be worked around.
  purchase_order_id bigint references public.purchase_orders (id) on delete set null,
  -- When the goods physically arrived, which is not the document's date —
  -- stock accuracy needs this one, the cost trail needs supplier_documents.doc_date.
  received_at       date not null default current_date,
  notes             text not null default '',
  created_at        timestamptz not null default now(),
  created_by        uuid references public.profiles (id) on delete set null
);

create index goods_receipts_supplier_received_idx
  on public.goods_receipts (supplier_id, received_at desc);

create index goods_receipts_po_idx
  on public.goods_receipts (purchase_order_id)
  where purchase_order_id is not null;

-- ── goods_receipt_items ───────────────────────────────────────────────────
create table public.goods_receipt_items (
  id                     bigint generated by default as identity primary key,
  goods_receipt_id       bigint not null references public.goods_receipts (id) on delete cascade,
  stock_id               bigint not null references public.stocks (id) on delete restrict,
  -- Nullable: supplies qty_ordered and the ordered price for the cross-check
  -- where the line matches an order, and is simply absent where it does not.
  purchase_order_item_id bigint references public.purchase_order_items (id) on delete set null,
  qty_received           integer not null check (qty_received > 0),
  -- Always ex-GST, normalised on the way in from the document's price_basis.
  -- Null where the document carried no prices at all (a docket).
  unit_cost_ex_gst       numeric,
  gst_applicable         boolean not null default true,
  line_note              text not null default '',
  created_at             timestamptz not null default now()
);

create index goods_receipt_items_receipt_idx
  on public.goods_receipt_items (goods_receipt_id);

create index goods_receipt_items_stock_idx
  on public.goods_receipt_items (stock_id);

create index goods_receipt_items_poi_idx
  on public.goods_receipt_items (purchase_order_item_id)
  where purchase_order_item_id is not null;

-- ── goods_receipt_documents ───────────────────────────────────────────────
create table public.goods_receipt_documents (
  goods_receipt_id     bigint not null references public.goods_receipts (id) on delete cascade,
  supplier_document_id bigint not null references public.supplier_documents (id) on delete cascade,
  primary key (goods_receipt_id, supplier_document_id)
);

create index goods_receipt_documents_doc_idx
  on public.goods_receipt_documents (supplier_document_id);

-- ── grants and RLS ────────────────────────────────────────────────────────
-- Revoke FIRST. This project carries an ALTER DEFAULT PRIVILEGES rule granting
-- ALL to anon and authenticated on every new table in public, so a bare grant
-- does not describe what the table ends up with (CLAUDE.md convention 5,
-- docs/bugs.md #13).
revoke all on public.supplier_documents       from anon, authenticated;
revoke all on public.goods_receipts           from anon, authenticated;
revoke all on public.goods_receipt_items      from anon, authenticated;
revoke all on public.goods_receipt_documents  from anon, authenticated;

alter table public.supplier_documents      enable row level security;
alter table public.goods_receipts          enable row level security;
alter table public.goods_receipt_items     enable row level security;
alter table public.goods_receipt_documents enable row level security;

-- supplier_documents: freely correctable by an admin. Editing a price or a
-- freight figure does not move stock, and fixing a misread number is the
-- expected workflow.
grant select, insert, update, delete on public.supplier_documents to authenticated;

create policy "supplier_documents_select_all" on public.supplier_documents
  for select to authenticated using (true);
create policy "supplier_documents_insert_admin" on public.supplier_documents
  for insert to authenticated with check ((select private.is_admin()));
create policy "supplier_documents_update_admin" on public.supplier_documents
  for update to authenticated
  using ((select private.is_admin())) with check ((select private.is_admin()));
create policy "supplier_documents_delete_admin" on public.supplier_documents
  for delete to authenticated using ((select private.is_admin()));

-- goods_receipts: UPDATE only, for metadata (received_at, notes, which PO it
-- is filed against). Creating or deleting a receipt has to move stock with it,
-- so both go through the RPC — SECURITY DEFINER, which bypasses RLS.
grant select, update on public.goods_receipts to authenticated;

create policy "goods_receipts_select_all" on public.goods_receipts
  for select to authenticated using (true);
create policy "goods_receipts_update_admin" on public.goods_receipts
  for update to authenticated
  using ((select private.is_admin())) with check ((select private.is_admin()));

-- goods_receipt_items: READ ONLY over PostgREST, with no write policy at all.
-- Changing qty_received or stock_id directly would desync stocks.qty — the
-- same class of bug CLAUDE.md convention 4 exists to prevent, where setting a
-- date directly bypassed stock consumption. Corrections must go through an RPC
-- that moves the stock too. Do not weaken this by adding a write policy.
grant select on public.goods_receipt_items to authenticated;

create policy "goods_receipt_items_select_all" on public.goods_receipt_items
  for select to authenticated using (true);

-- goods_receipt_documents: attaching a late invoice to an existing receipt is
-- a linking action with no stock consequence, so admins may do it directly.
grant select, insert, delete on public.goods_receipt_documents to authenticated;

create policy "goods_receipt_documents_select_all" on public.goods_receipt_documents
  for select to authenticated using (true);
create policy "goods_receipt_documents_insert_admin" on public.goods_receipt_documents
  for insert to authenticated with check ((select private.is_admin()));
create policy "goods_receipt_documents_delete_admin" on public.goods_receipt_documents
  for delete to authenticated using ((select private.is_admin()));

grant usage, select on sequence public.supplier_documents_id_seq to authenticated;

comment on table public.goods_receipts is
  'A stock movement event. Separate from purchase_orders so one order can be received several times, and from supplier_documents so stock moves once while prices can arrive later.';
comment on table public.supplier_documents is
  'A delivery docket or supplier invoice. Many-to-many with receipts: one invoice can cover two deliveries, one delivery can be split across two invoices.';
comment on table public.goods_receipt_items is
  'Receipt lines. Read-only via PostgREST — writes go through the receive_goods RPC so stocks.qty cannot drift from what was received.';
