-- 100UP CRM — AI call log.
--
-- One row per aiComplete() call, for auditability and cost tracking. The
-- input is never stored — only what came back, which model produced it, and
-- what it cost. For invoice extraction the input is a supplier PDF that
-- belongs in the receipt trail, not duplicated into a log table.
--
-- tokens_in and tokens_out are kept apart because Anthropic prices them very
-- differently (output runs ~5x input); a single "tokens used" figure cannot
-- be costed. tokens_used is a generated sum for simple display.

create table public.ai_call_log (
  id          bigint generated by default as identity primary key,
  purpose     text    not null,
  -- Pointer back to the source record (receipt id, invoice ref, thread id).
  input_ref   text,
  output      text    not null,
  model_used  text    not null,
  tokens_in   integer not null default 0,
  tokens_out  integer not null default 0,
  tokens_used integer generated always as (tokens_in + tokens_out) stored,
  created_at  timestamptz not null default now()
);

create index ai_call_log_created_at_idx on public.ai_call_log (created_at desc);
create index ai_call_log_purpose_idx    on public.ai_call_log (purpose, created_at desc);

alter table public.ai_call_log enable row level security;

-- Admin only — this is spend data. Inserts come from Edge Functions on the
-- service role, so there is no insert policy for authenticated.
create policy "ai_call_log_select_admin"
  on public.ai_call_log for select to authenticated
  using ((select private.is_admin()));

grant select on public.ai_call_log to authenticated;

comment on table public.ai_call_log is
  'One row per AI call. Metadata and output only — the prompt input is never stored. Feeds the monthly cost estimate in Settings.';
