-- 100UP CRM — Phase 2 migration: customers, installation_requests,
-- date renames, profile notification fields.
--
-- Applied directly to the live DB via execute_sql on 2026-07-19.
-- This file is the authoritative record of those changes.
-- See docs/schema-restructure-proposal.md for full design rationale.
--
-- Scope:
--   §1  customers table  (split from jobs.name/email/phone/contact_method)
--   §2  installation_requests table  (replaces jobs.job_order jsonb)
--   §3  jobs date column renames  (planned_install_date, install_start_date,
--                                   install_completion_date)
--   §4  profiles notification columns
--   Guard trigger + advance/moveback/reschedule RPCs updated for new names.
--   RLS, grants, Realtime publications for new tables.
--
-- NOT in this migration: manufacturer normalization (§7) — see proposal doc.

-- ── §1 customers ──────────────────────────────────────────────────────
create table public.customers (
  id             bigint generated by default as identity primary key,
  name           text   not null,
  address        text   not null default '',   -- optional mailing address; distinct from jobs.location
  phone          text   not null default '',
  email          text   not null default '',
  contact_method text   not null default 'Email',
  version        integer not null default 1,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create or replace function private.bump_customer_version()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;

create trigger b_bump_customer_version
  before update on public.customers
  for each row execute function private.bump_customer_version();

-- RLS
revoke all on public.customers from anon;
grant select, insert, update, delete on public.customers to authenticated;
grant usage, select on sequence public.customers_id_seq to authenticated;

alter table public.customers enable row level security;

-- Installers can SELECT a customer reachable through a job assigned to them
create policy "customers_select_admin_or_via_job" on public.customers
  for select to authenticated
  using (
    (select private.is_admin())
    or exists (
      select 1 from public.jobs j
      where j.customer_id = customers.id
        and j.assigned_installer_id = (select auth.uid())
    )
  );

create policy "customers_insert_admin" on public.customers
  for insert to authenticated
  with check ((select private.is_admin()));

create policy "customers_update_admin" on public.customers
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

create policy "customers_delete_admin" on public.customers
  for delete to authenticated
  using ((select private.is_admin()));


-- ── §2 installation_requests ──────────────────────────────────────────
-- job_id is the PK (1:1 extension, mirrors stock_ces_specs pattern).
-- Dropped from old jsonb shape: systemDesc (dup of jobs.system_description),
-- installer (superseded by jobs.assigned_installer_id).
-- savedAt → updated_at (maintained by bump trigger).
create table public.installation_requests (
  job_id                bigint primary key references public.jobs(id) on delete cascade,
  job_order_ref         text   not null default '',
  issued_date           date,
  vehicle               text   not null default '',
  site_access_notes     text   not null default '',
  special_instructions  text   not null default '',
  additional_notes      text   not null default '',
  custom_items          jsonb  not null default '[]'::jsonb,
  version               integer not null default 1,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create or replace function private.bump_installation_request_version()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;

create trigger b_bump_installation_request_version
  before update on public.installation_requests
  for each row execute function private.bump_installation_request_version();

-- RLS
revoke all on public.installation_requests from anon;
grant select, insert, update, delete on public.installation_requests to authenticated;

alter table public.installation_requests enable row level security;

create policy "installation_requests_select_admin_or_assigned"
  on public.installation_requests
  for select to authenticated
  using (
    (select private.is_admin())
    or exists (
      select 1 from public.jobs j
      where j.id = installation_requests.job_id
        and j.assigned_installer_id = (select auth.uid())
    )
  );

create policy "installation_requests_insert_admin" on public.installation_requests
  for insert to authenticated
  with check ((select private.is_admin()));

create policy "installation_requests_update_admin" on public.installation_requests
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

create policy "installation_requests_delete_admin" on public.installation_requests
  for delete to authenticated
  using ((select private.is_admin()));


-- ── Data back-fill (trial data only — see proposal §Execution plan §4) ─
-- At real cutover this section is replaced by import_from_export.py output.

-- One customer per trial job (all unique name+phone in the trial dataset)
insert into public.customers (name, phone, email, contact_method)
select name, phone, email, contact_method
from public.jobs
order by id;

-- Back-fill installation_requests from job_order jsonb
-- Drops systemDesc (dup), installer (superseded). savedAt preserved as created_at.
insert into public.installation_requests
  (job_id, job_order_ref, issued_date, vehicle,
   site_access_notes, special_instructions, additional_notes,
   custom_items, created_at)
select
  id,
  coalesce(job_order->>'ref', ''),
  nullif(job_order->>'issued', '')::date,
  coalesce(job_order->>'vehicle', ''),
  coalesce(job_order->>'siteAccess', ''),
  coalesce(job_order->>'specialInstructions', ''),
  coalesce(job_order->>'extraNotes', ''),
  coalesce(job_order->'customItems', '[]'::jsonb),
  to_timestamp((job_order->>'savedAt')::bigint / 1000)
from public.jobs
where job_order is not null;


-- ── §4 profiles notification columns ─────────────────────────────────
alter table public.profiles
  add column if not exists notification_email text,
  add column if not exists notification_phone text;


-- ── §1 alter jobs: add customer_id, drop moved columns ───────────────
-- Add nullable first so back-fill can run, then enforce NOT NULL.
alter table public.jobs
  add column customer_id bigint references public.customers(id) on delete restrict;

-- Link each job to its customer
update public.jobs j
set customer_id = c.id
from public.customers c
where j.name = c.name;

alter table public.jobs alter column customer_id set not null;

create index jobs_customer_id_idx on public.jobs (customer_id);

-- Drop columns that moved to customers / installation_requests
alter table public.jobs
  drop column name,
  drop column email,
  drop column phone,
  drop column contact_method,
  drop column job_order;


-- ── §3 date column renames ────────────────────────────────────────────
-- Columns remain PostgreSQL date type; _date suffix used (not _at).
alter table public.jobs rename column date_booked   to planned_install_date;
alter table public.jobs rename column install_start  to install_start_date;
alter table public.jobs rename column install_date   to install_completion_date;


-- ── Updated guard trigger ──────────────────────────────────────────────
-- Removes checks for dropped columns; uses renamed date names;
-- adds customer_id to the admin-only protected set.
create or replace function private.guard_jobs_update()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_flag_on   boolean := coalesce(current_setting('app.allow_stage_writes', true), '') = 'on';
  v_direct    boolean := (select auth.uid()) is null;
begin
  if not (v_flag_on or v_direct) then
    if new.stage                     is distinct from old.stage
      or new.step                    is distinct from old.step
      or new.planned_install_date    is distinct from old.planned_install_date
      or new.install_start_date      is distinct from old.install_start_date
      or new.install_completion_date is distinct from old.install_completion_date
      or new.ces_submitted           is distinct from old.ces_submitted
      or new.ces_received            is distinct from old.ces_received
      or new.rebate_submitted        is distinct from old.rebate_submitted
      or new.rebate_received         is distinct from old.rebate_received
    then
      raise exception 'stage_write_blocked: stage, step and pipeline dates change only via advance_job_stage / move_job_back / reschedule_booking';
    end if;

    -- Installers may only touch notes and fixes_needed directly.
    if not coalesce((select private.is_admin()), false) then
      if new.location              is distinct from old.location
        or new.system_description  is distinct from old.system_description
        or new.value               is distinct from old.value
        or new.job_type            is distinct from old.job_type
        or new.assigned_installer_id is distinct from old.assigned_installer_id
        or new.customer_id         is distinct from old.customer_id
      then
        raise exception 'installer_edit_blocked: installers can only edit notes and the fixes flag';
      end if;
    end if;
  end if;
  return new;
end;
$$;


-- ── Updated advance_job_stage ──────────────────────────────────────────
create or replace function public.advance_job_stage(
  p_job_id bigint,
  p_expected_version integer,
  p_date date default null,
  p_override_stage smallint default null,
  p_override_step smallint default null
) returns public.jobs
language plpgsql
security definer
set search_path = ''
as $$
declare
  j          public.jobs%rowtype;
  v_max_step smallint;
  v_stage    smallint;
  v_step     smallint;
  v_today    date := (now() at time zone 'Australia/Melbourne')::date;
begin
  j := private.lock_job_for_transition(p_job_id, p_expected_version);

  select max(step) into v_max_step
  from public.pipeline_steps where stage = j.stage;

  if p_override_stage is not null then
    v_stage := p_override_stage;
    v_step  := coalesce(p_override_step, 0);
  elsif j.step < v_max_step then
    v_stage := j.stage;
    v_step  := j.step + 1;
  elsif j.stage < 4 then
    v_stage := j.stage + 1;
    v_step  := 0;
  else
    return j;
  end if;

  perform set_config('app.allow_stage_writes', 'on', true);

  update public.jobs set
    stage                   = v_stage,
    step                    = v_step,
    planned_install_date    = case when v_stage = 3 and v_step = 1
                                   then coalesce(p_date, v_today) else planned_install_date end,
    install_start_date      = case when v_stage = 3 and v_step = 3
                                   then coalesce(p_date, v_today) else install_start_date end,
    install_completion_date = case when v_stage = 3 and v_step = 4
                                   then coalesce(p_date, v_today) else install_completion_date end,
    ces_submitted           = case when v_stage = 4 and v_step = 0
                                   then v_today else ces_submitted end,
    ces_received            = case when v_stage = 4 and v_step = 3
                                   then v_today else ces_received end,
    rebate_submitted        = case when v_stage = 4 and v_step = 4
                                   then v_today else rebate_submitted end,
    rebate_received         = case when v_stage = 4 and v_step = 5
                                   then v_today else rebate_received end
  where id = p_job_id;

  if v_stage = 3 and v_step = 1 then
    perform private.apply_pending_bom(p_job_id);
  end if;

  if v_stage = 3 and v_step = 3 then
    update public.stocks s
    set qty = greatest(0, s.qty - c.total)
    from (
      select stock_id, sum(qty) as total
      from public.job_stock_items
      where job_id = p_job_id and status = 'assigned'
      group by stock_id
    ) c
    where s.id = c.stock_id;

    with moved as (
      delete from public.job_stock_items
      where job_id = p_job_id and status = 'assigned'
      returning stock_id, qty, notes, assigned_at
    )
    insert into public.job_stock_items
      (job_id, stock_id, qty, notes, status, assigned_at, consumed_at)
    select p_job_id, stock_id, qty, notes, 'consumed', assigned_at, now()
    from moved
    on conflict (job_id, stock_id, status)
    do update set qty = public.job_stock_items.qty + excluded.qty,
                  consumed_at = excluded.consumed_at;
  end if;

  insert into public.job_events (job_id, event_type, payload, actor)
  values (
    p_job_id, 'stage_advanced',
    jsonb_build_object(
      'from', jsonb_build_object('stage', j.stage, 'step', j.step),
      'to',   jsonb_build_object('stage', v_stage, 'step', v_step)
    ),
    (select auth.uid())
  );

  select * into j from public.jobs where id = p_job_id;
  return j;
end;
$$;


-- ── Updated move_job_back ──────────────────────────────────────────────
create or replace function public.move_job_back(
  p_job_id bigint,
  p_expected_version integer
) returns public.jobs
language plpgsql
security definer
set search_path = ''
as $$
declare
  j            public.jobs%rowtype;
  v_stage      smallint;
  v_step       smallint;
  v_same_stage boolean;
begin
  j := private.lock_job_for_transition(p_job_id, p_expected_version);

  if j.step > 0 then
    v_stage := j.stage;
    v_step  := j.step - 1;
    v_same_stage := true;
  elsif j.stage > 1 then
    v_stage := j.stage - 1;
    select max(step) into v_step
    from public.pipeline_steps where stage = v_stage;
    v_same_stage := false;
  else
    return j;
  end if;

  perform set_config('app.allow_stage_writes', 'on', true);

  -- Restore stock when stepping back off (3,3) — faithful to V46 lines 7449-7458
  if v_same_stage and j.stage = 3 and j.step = 3 then
    update public.stocks s
    set qty = s.qty + c.total
    from (
      select stock_id, sum(qty) as total
      from public.job_stock_items
      where job_id = p_job_id and status = 'consumed'
      group by stock_id
    ) c
    where s.id = c.stock_id;

    with moved as (
      delete from public.job_stock_items
      where job_id = p_job_id and status = 'consumed'
      returning stock_id, qty, notes, assigned_at
    )
    insert into public.job_stock_items
      (job_id, stock_id, qty, notes, status, assigned_at)
    select p_job_id, stock_id, qty, notes, 'assigned', coalesce(assigned_at, now())
    from moved
    on conflict (job_id, stock_id, status)
    do update set qty = public.job_stock_items.qty + excluded.qty;
  end if;

  update public.jobs set
    stage = v_stage,
    step  = v_step,
    rebate_received        = case
        when v_same_stage and v_stage = 4 and v_step < 5 then null
        when not v_same_stage and v_stage = 3 then null
        else rebate_received end,
    rebate_submitted       = case
        when v_same_stage and v_stage = 4 and v_step < 4 then null
        when not v_same_stage and v_stage = 3 then null
        else rebate_submitted end,
    ces_received           = case
        when v_same_stage and v_stage = 4 and v_step < 3 then null
        when not v_same_stage and v_stage = 3 then null
        else ces_received end,
    ces_submitted          = case
        when v_same_stage and v_stage = 4 and v_step < 1 then null
        when not v_same_stage and v_stage = 3 then null
        else ces_submitted end,
    install_completion_date = case
        when v_same_stage and v_stage = 3 and v_step < 4 then null
        else install_completion_date end,
    install_start_date     = case
        when v_same_stage and v_stage = 3 and v_step < 3 then null
        else install_start_date end,
    planned_install_date   = case
        when v_same_stage and v_stage = 3 and v_step < 1 then null
        else planned_install_date end
  where id = p_job_id;

  insert into public.job_events (job_id, event_type, payload, actor)
  values (
    p_job_id, 'stage_moved_back',
    jsonb_build_object(
      'from', jsonb_build_object('stage', j.stage, 'step', j.step),
      'to',   jsonb_build_object('stage', v_stage, 'step', v_step)
    ),
    (select auth.uid())
  );

  select * into j from public.jobs where id = p_job_id;
  return j;
end;
$$;


-- ── Updated reschedule_booking (replaces migration-004 version) ────────
create or replace function public.reschedule_booking(
  p_job_id bigint,
  p_expected_version integer,
  p_new_date date
) returns public.jobs
language plpgsql
security definer
set search_path = ''
as $$
declare
  j public.jobs%rowtype;
begin
  if not private.is_elevated() then
    raise exception 'not_allowed: admin only';
  end if;

  j := private.lock_job_for_transition(p_job_id, p_expected_version);

  perform set_config('app.allow_stage_writes', 'on', true);

  update public.jobs set planned_install_date = p_new_date where id = p_job_id;
  perform private.apply_pending_bom(p_job_id);

  insert into public.job_events (job_id, event_type, payload, actor)
  values (
    p_job_id, 'booking_rescheduled',
    jsonb_build_object('from', j.planned_install_date, 'to', p_new_date),
    (select auth.uid())
  );

  select * into j from public.jobs where id = p_job_id;
  return j;
end;
$$;


-- ── Realtime publications ─────────────────────────────────────────────
alter publication supabase_realtime add table public.customers;
alter publication supabase_realtime add table public.installation_requests;
