-- 100UP CRM — Purchase Orders.
--
-- Renames receipts -> purchase_orders and gives it a real lifecycle
-- (sent -> partially_received -> closed) instead of only ever
-- representing a completed delivery. Adds purchase_order_items to
-- track ordered vs received qty and cost per line.
--
-- receive_stock still creates its own implicit, already-closed PO for
-- the ad-hoc "just paste an invoice" flow — that flow is unchanged
-- tonight. Wiring "receive against an open PO" is a follow-up; direct
-- ad-hoc receiving will be retired once that lands (tracked in
-- docs/bugs.md).

create sequence public.purchase_order_ref_seq;

create type public.po_status as enum ('sent', 'partially_received', 'closed');

alter table public.receipts rename to purchase_orders;
alter index receipts_supplier_id_idx rename to purchase_orders_supplier_id_idx;

alter table public.purchase_orders
  add column po_ref    text,
  add column po_amount numeric not null default 0 check (po_amount >= 0),
  add column po_status public.po_status not null default 'sent';

-- Existing rows are legacy ad-hoc receipts: no "ordered" stage ever
-- existed for them, so they're retroactively closed. No per-line cost
-- history exists for them either (bug #4), so po_amount stays 0.
update public.purchase_orders
set po_ref    = 'PO-' || to_char(created_at, 'YYYYMMDD') || '-' || nextval('purchase_order_ref_seq'),
    po_status = 'closed'
where po_ref is null;

alter table public.purchase_orders
  alter column po_ref set not null,
  alter column po_ref set default ('PO-' || to_char(now(), 'YYYYMMDD') || '-' || nextval('purchase_order_ref_seq')),
  add constraint purchase_orders_po_ref_uq unique (po_ref);

alter policy "receipts_select_all"   on public.purchase_orders rename to "purchase_orders_select_all";
alter policy "receipts_insert_admin" on public.purchase_orders rename to "purchase_orders_insert_admin";
alter policy "receipts_update_admin" on public.purchase_orders rename to "purchase_orders_update_admin";
alter policy "receipts_delete_admin" on public.purchase_orders rename to "purchase_orders_delete_admin";

create table public.purchase_order_items (
  id                bigint generated by default as identity primary key,
  purchase_order_id bigint  not null references public.purchase_orders (id) on delete cascade,
  stock_id          bigint  not null references public.stocks (id) on delete restrict,
  qty_ordered       integer not null check (qty_ordered > 0),
  cost              numeric not null default 0 check (cost >= 0),
  qty_received      integer not null default 0 check (qty_received >= 0 and qty_received <= qty_ordered),
  created_at        timestamptz not null default now()
);

create index purchase_order_items_po_idx    on public.purchase_order_items (purchase_order_id);
create index purchase_order_items_stock_idx on public.purchase_order_items (stock_id);

alter table public.purchase_order_items enable row level security;

create policy "purchase_order_items_select_all" on public.purchase_order_items
  for select to authenticated using (true);
create policy "purchase_order_items_insert_admin" on public.purchase_order_items
  for insert to authenticated with check ((select private.is_admin()));
create policy "purchase_order_items_update_admin" on public.purchase_order_items
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));
create policy "purchase_order_items_delete_admin" on public.purchase_order_items
  for delete to authenticated using ((select private.is_admin()));

grant select on public.purchase_order_items to authenticated;
grant insert, update, delete on public.purchase_order_items to authenticated;
grant usage, select on public.purchase_order_ref_seq to authenticated;

-- ── create_purchase_order ──────────────────────────────────────────────
-- Called from Order List "Save PO". Lines: [{stock_id, qty_ordered, cost}].
-- po_ref comes from the column default; po_amount/item_count/total_units
-- are computed from the lines actually inserted.
create or replace function public.create_purchase_order(
  p_supplier_id bigint,
  p_lines jsonb
) returns public.purchase_orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  l          jsonb;
  v_qty      integer;
  v_cost     numeric;
  v_count    integer := 0;
  v_units    integer := 0;
  v_amount   numeric := 0;
  v_po_id    bigint;
  r          public.purchase_orders%rowtype;
begin
  if not private.is_elevated() then
    raise exception 'not_allowed: admin only';
  end if;

  if p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'invalid_lines: expected a non-empty array of {stock_id, qty_ordered, cost}';
  end if;

  if p_supplier_id is not null
     and not exists (select 1 from public.suppliers where id = p_supplier_id) then
    raise exception 'supplier_not_found: supplier % does not exist', p_supplier_id;
  end if;

  insert into public.purchase_orders (supplier_id, po_status)
  values (p_supplier_id, 'sent')
  returning id into v_po_id;

  for l in select * from jsonb_array_elements(p_lines)
  loop
    v_qty  := coalesce((l ->> 'qty_ordered')::integer, 0);
    v_cost := coalesce((l ->> 'cost')::numeric, 0);
    if v_qty <= 0 or not (l ? 'stock_id') then
      continue;
    end if;

    insert into public.purchase_order_items (purchase_order_id, stock_id, qty_ordered, cost)
    values (v_po_id, (l ->> 'stock_id')::bigint, v_qty, v_cost);

    v_count  := v_count + 1;
    v_units  := v_units + v_qty;
    v_amount := v_amount + (v_qty * v_cost);
  end loop;

  if v_count = 0 then
    raise exception 'invalid_lines: no line had a valid stock_id and positive qty_ordered';
  end if;

  update public.purchase_orders
  set item_count = v_count, total_units = v_units, po_amount = v_amount
  where id = v_po_id
  returning * into r;

  return r;
end;
$$;

revoke all on function public.create_purchase_order(bigint, jsonb) from public, anon;
grant execute on function public.create_purchase_order(bigint, jsonb) to authenticated;

-- receive_stock now writes into purchase_orders — an ad-hoc receipt with
-- no prior order is inherently already fully received.
create or replace function public.receive_stock(
  p_supplier_id bigint,
  p_invoice_ref text,
  p_occurred_at date,
  p_lines jsonb
) returns public.purchase_orders
language plpgsql
security definer
set search_path = ''
as $$
declare
  l           jsonb;
  v_stock_id  bigint;
  v_qty       integer;
  v_count     integer := 0;
  v_units     integer := 0;
  r           public.purchase_orders%rowtype;
begin
  if not private.is_elevated() then
    raise exception 'not_allowed: admin only';
  end if;

  if p_lines is null or jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) = 0 then
    raise exception 'invalid_lines: expected a non-empty array of {stock_id|new_name, qty}';
  end if;

  if p_supplier_id is not null
     and not exists (select 1 from public.suppliers where id = p_supplier_id) then
    raise exception 'supplier_not_found: supplier % does not exist', p_supplier_id;
  end if;

  for l in select * from jsonb_array_elements(p_lines)
  loop
    v_qty := coalesce((l ->> 'qty')::integer, 0);
    if v_qty <= 0 then
      continue;
    end if;

    if l ? 'stock_id' then
      v_stock_id := (l ->> 'stock_id')::bigint;
      update public.stocks set qty = qty + v_qty where id = v_stock_id;
      if not found then
        raise exception 'stock_not_found: stock item % does not exist', v_stock_id;
      end if;
    elsif coalesce(trim(l ->> 'new_name'), '') <> '' then
      insert into public.stocks (name, qty, preferred_supplier_id)
      values (trim(l ->> 'new_name'), v_qty, p_supplier_id);
    else
      raise exception 'invalid_line: each line needs stock_id or new_name (%)', l::text;
    end if;

    v_count := v_count + 1;
    v_units := v_units + v_qty;
  end loop;

  if v_count = 0 then
    raise exception 'invalid_lines: no line had a positive quantity';
  end if;

  insert into public.purchase_orders (supplier_id, invoice_ref, occurred_at, item_count, total_units, po_status)
  values (p_supplier_id, p_invoice_ref, p_occurred_at, v_count, v_units, 'closed')
  returning * into r;

  return r;
end;
$$;
