-- 100UP CRM — configurable Simulation quick-fills.
--
-- Fixes bug #2. V46's quick-fill buttons were a hybrid: battery kWh was pulled
-- live from assumptions, but the panel counts (30/36) and which unit-count
-- combinations were offered (Sig 3/4, Deye 5/6) were hardcoded literals. So
-- editing assumptions changed the numbers on the buttons but not which
-- scenarios existed, and nobody could add a fifth.
--
-- Now they are rows. Capped at six because they are shortcuts on one screen —
-- past that they stop being quick.

create table public.simulation_presets (
  id             bigint generated by default as identity primary key,
  label          text    not null,
  -- Optional. When set, the preset also adopts that inverter's system config
  -- standby draw, which is the figure most likely to be got wrong by hand.
  inverter_stock_id bigint references public.stocks (id) on delete set null,
  inverter_count integer not null default 1 check (inverter_count > 0),
  battery_units  integer not null default 1 check (battery_units > 0),
  panel_count    integer not null default 0 check (panel_count >= 0),
  sort_order     smallint not null default 0
);

-- Six is a UI limit, so enforce it where it cannot be bypassed.
create or replace function private.cap_simulation_presets()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if (select count(*) from public.simulation_presets) >= 6 then
    raise exception 'preset_limit: at most 6 simulation quick-fills';
  end if;
  return new;
end;
$$;

create trigger a_cap_simulation_presets
  before insert on public.simulation_presets
  for each row execute function private.cap_simulation_presets();

-- Seed four, mirroring the combinations V46 hardcoded (Sig 3/4, Deye 5/6)
-- but now as data. Panel counts were 30/36 there; kept, and editable.
insert into public.simulation_presets (label, inverter_stock_id, inverter_count, battery_units, panel_count, sort_order)
select 'Sigenergy 3 × battery',  s.id, 1, 3, 30, 1 from public.stocks s where s.name = 'SigenStor EC 8.0 SP'
union all
select 'Sigenergy 4 × battery',  s.id, 1, 4, 36, 2 from public.stocks s where s.name = 'SigenStor EC 8.0 SP'
union all
select 'Deye 5 × battery',       s.id, 1, 5, 30, 3 from public.stocks s where s.name = 'Deye AI-W5.1-8P1-AU-B'
union all
select 'Deye 6 × battery',       s.id, 1, 6, 36, 4 from public.stocks s where s.name = 'Deye AI-W5.1-8P1-AU-B';

revoke all on public.simulation_presets from anon;
grant select on public.simulation_presets to authenticated;
grant insert, update, delete on public.simulation_presets to authenticated;
grant usage, select on sequence public.simulation_presets_id_seq to authenticated;

alter table public.simulation_presets enable row level security;

create policy "simulation_presets_select_all" on public.simulation_presets
  for select to authenticated using (true);

create policy "simulation_presets_write_admin" on public.simulation_presets
  for all to authenticated
  using ((select private.is_admin())) with check ((select private.is_admin()));

alter publication supabase_realtime add table public.simulation_presets;

comment on table public.simulation_presets is
  'Simulation quick-fills. Replaces V46 hardcoded scenario buttons (bug #2) — the combinations themselves are now editable, not just the figures shown on them.';
